import { createPublicClient, http } from "viem";
import deployment from "../../../docs/ethonline-2026/proof/hedera-facility-deployment.json";
import ensEvidence from "../../../docs/ethonline-2026/proof/ensv2-authority.json";
import { HEDERA_FACILITY } from "./institutional-proof";

const RPC = "https://testnet.hashio.io/api";
const SEPOLIA_RPC = process.env.SEPOLIA_RPC_URL ?? "https://ethereum-sepolia-rpc.publicnode.com";
const STATUS = ["DRAFT", "PENDING_ACTIVATION", "ACTIVE", "SUBSTITUTION_PENDING", "RECALLING", "MATURED", "SETTLED", "DEFAULTED"] as const;
const SUBSTITUTION = ["NONE", "REQUESTED", "REPLACEMENT_COMMITTING", "COMMITMENT_UNKNOWN", "REPLACEMENT_COMMITTED"] as const;
const FACILITY = [
  { name: "status", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { name: "riskEpochAtActivation", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint64" }] },
  { name: "policies", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { name: "authorityVerifier", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { name: "policyVerifier", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { name: "collateral", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "tuple", components: [{ name: "assetId", type: "bytes32" }, { name: "instrumentRef", type: "bytes32" }, { name: "adapter", type: "address" }, { name: "committedUnits", type: "uint256" }, { name: "passportVersion", type: "uint64" }] }] },
  { name: "substitution", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "tuple", components: [{ name: "state", type: "uint8" }, { name: "consumed", type: "bool" }, { name: "id", type: "bytes32" }, { name: "replacementAssetId", type: "bytes32" }, { name: "replacementInstrumentRef", type: "bytes32" }, { name: "replacementAdapter", type: "address" }, { name: "requiredUnits", type: "uint256" }, { name: "pinnedEpoch", type: "uint64" }, { name: "collateralPolicyVersion", type: "uint64" }, { name: "authorityExpiry", type: "uint64" }, { name: "policyDecisionHash", type: "bytes32" }, { name: "authorityDecisionHash", type: "bytes32" }, { name: "lastReason", type: "bytes32" }] }] },
] as const;
const ADAPTER = [{ name: "assetId", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "bytes32" }] }, { name: "instrumentRef", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "bytes32" }] }, { name: "canCommit", type: "function", stateMutability: "view", inputs: [{ type: "address" }], outputs: [{ type: "bool" }, { type: "bytes32" }] }, { name: "transferable", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }, { type: "bytes32" }] }, { name: "committedOf", type: "function", stateMutability: "view", inputs: [{ type: "address" }], outputs: [{ type: "uint256" }] }] as const;
const RISK = [{ name: "riskEpoch", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint64" }] }] as const;
const AUTHORITY = [{ name: "facilityAuthority", type: "function", stateMutability: "view", inputs: [{ type: "bytes32" }], outputs: [{ type: "tuple", components: [{ type: "address" }, { type: "bytes32" }, { type: "bool" }, { type: "bool" }] }] }] as const;
const POLICY = [{ name: "facilityPolicy", type: "function", stateMutability: "view", inputs: [{ type: "bytes32" }], outputs: [{ type: "tuple", components: [{ type: "address" }, { type: "bytes32" }, { type: "uint32" }, { type: "bool" }] }] }] as const;
const ENS = [{ name: "hasRoles", type: "function", stateMutability: "view", inputs: [{ type: "uint256" }, { type: "uint256" }, { type: "address" }], outputs: [{ type: "bool" }] }] as const;

export type SubstitutionReadiness = { outcome: "PREPARATION_READY" | "FACILITY_UNAVAILABLE" | "FACILITY_NOT_ACTIVE" | "SUBSTITUTION_ALREADY_PENDING" | "COMMITMENT_UNKNOWN" | "ATS_RESTRICTED" | "AUTHORITY_REVOKED" | "AUTHORITY_REQUIRED" | "CRE_REQUIRED" | "REPLACEMENT_UNSAFE"; facilityId: string; homeDomain: "hedera:testnet:296"; observedAt: string; observedAtBlock: string; request: { replacement: string; requestedUnits: string }; current: { facilityStatus: string; riskEpoch: string; collateralAssetId: string; collateralInstrumentRef: string; collateralCommittedUnits: string; substitutionState: string }; replacementIdentity: { assetId: string; instrumentRef: string; adapter: string } | null; checks: { ats: { canCommit: boolean; transferable: boolean; committedUnits: string; reason: string | null }; authority: { configured: boolean; revoked: boolean; ensRoleLive: boolean }; policy: { configured: boolean; mode: "LIVE_SIMULATION" } }; finalFinancialSafety: { state: "ENFORCED_AT_RELEASE" | "BLOCKED"; previewAvailable: false }; blockingReasons: string[]; proofReferences: string[] };

const replacements = Object.entries(deployment.contracts).filter(([key]) => /^Adapter[ABC]$/.test(key)).map(([key, adapter]) => ({ key: key.slice(-1), adapter: adapter as `0x${string}` }));

export async function readSubstitutionReadiness(replacement: string, requestedUnits: bigint): Promise<SubstitutionReadiness> {
  const candidate = replacements.find((item) => item.key.toLowerCase() === replacement.toLowerCase());
  if (!candidate || requestedUnits <= 0n) return unavailable(replacement, requestedUnits, "REPLACEMENT_UNSAFE", "Replacement selection or requested units are invalid.");
  const client = createPublicClient({ transport: http(RPC, { timeout: 12_000, retryCount: 1 }) }); const sepolia = createPublicClient({ transport: http(SEPOLIA_RPC, { timeout: 12_000, retryCount: 1 }) });
  try {
    const blockNumber = await client.getBlockNumber(); const block = await client.getBlock({ blockNumber }); const facility = deployment.contracts.InstitutionalFacility as `0x${string}`;
    const [status, policies, authorityVerifier, policyVerifier, collateral, substitution] = await Promise.all([
      client.readContract({ address: facility, abi: FACILITY, functionName: "status", blockNumber }), client.readContract({ address: facility, abi: FACILITY, functionName: "policies", blockNumber }), client.readContract({ address: facility, abi: FACILITY, functionName: "authorityVerifier", blockNumber }), client.readContract({ address: facility, abi: FACILITY, functionName: "policyVerifier", blockNumber }), client.readContract({ address: facility, abi: FACILITY, functionName: "collateral", blockNumber }), client.readContract({ address: facility, abi: FACILITY, functionName: "substitution", blockNumber }),
    ]);
    const [epoch, authority, policy, candidateAssetId, candidateInstrumentRef, canCommit, transferable, committedUnits, ensRoleLive] = await Promise.all([
      client.readContract({ address: policies, abi: RISK, functionName: "riskEpoch", blockNumber }), client.readContract({ address: authorityVerifier, abi: AUTHORITY, functionName: "facilityAuthority", args: [HEDERA_FACILITY.id as `0x${string}`], blockNumber }), client.readContract({ address: policyVerifier, abi: POLICY, functionName: "facilityPolicy", args: [HEDERA_FACILITY.id as `0x${string}`], blockNumber }), client.readContract({ address: candidate.adapter, abi: ADAPTER, functionName: "assetId", blockNumber }), client.readContract({ address: candidate.adapter, abi: ADAPTER, functionName: "instrumentRef", blockNumber }), client.readContract({ address: candidate.adapter, abi: ADAPTER, functionName: "canCommit", args: [facility], blockNumber }), client.readContract({ address: candidate.adapter, abi: ADAPTER, functionName: "transferable", blockNumber }), client.readContract({ address: candidate.adapter, abi: ADAPTER, functionName: "committedOf", args: [facility], blockNumber }), sepolia.readContract({ address: ensEvidence.ensv2.ethRegistry as `0x${string}`, abi: ENS, functionName: "hasRoles", args: [BigInt(ensEvidence.labelhash), BigInt(ensEvidence.roleBitmap), ensEvidence.delegate as `0x${string}`] }),
    ]);
    const currentStatus = STATUS[Number(status)] ?? "UNKNOWN"; const substitutionState = SUBSTITUTION[Number(substitution.state)] ?? "UNKNOWN"; const reasons: string[] = [];
    let outcome: SubstitutionReadiness["outcome"] = "PREPARATION_READY";
    if (currentStatus !== "ACTIVE") { outcome = "FACILITY_NOT_ACTIVE"; reasons.push(`Facility status is ${currentStatus}.`); }
    else if (substitutionState === "COMMITMENT_UNKNOWN") { outcome = "COMMITMENT_UNKNOWN"; reasons.push("An existing commitment requires authoritative reconciliation."); }
    else if (substitutionState !== "NONE") { outcome = "SUBSTITUTION_ALREADY_PENDING"; reasons.push("Only one substitution may be active."); }
    else if (!canCommit[0] || !transferable[0]) { outcome = "ATS_RESTRICTED"; reasons.push("The proposed ATS replacement is currently restricted."); }
    else if (!authority[3]) { outcome = "AUTHORITY_REQUIRED"; reasons.push("The facility has no configured authority verifier."); }
    else if (authority[2] || !ensRoleLive) { outcome = "AUTHORITY_REVOKED"; reasons.push("The current ENS authority is revoked or absent; historical proof cannot authorize a new request."); }
    else if (!policy[3]) { outcome = "CRE_REQUIRED"; reasons.push("The confidential-policy verifier is not configured."); }
    return { outcome, facilityId: HEDERA_FACILITY.id, homeDomain: "hedera:testnet:296", observedAt: new Date(Number(block.timestamp) * 1000).toISOString(), observedAtBlock: blockNumber.toString(), request: { replacement: candidate.key, requestedUnits: requestedUnits.toString() }, current: { facilityStatus: currentStatus, riskEpoch: epoch.toString(), collateralAssetId: collateral.assetId, collateralInstrumentRef: collateral.instrumentRef, collateralCommittedUnits: collateral.committedUnits.toString(), substitutionState }, replacementIdentity: { assetId: candidateAssetId, instrumentRef: candidateInstrumentRef, adapter: candidate.adapter }, checks: { ats: { canCommit: canCommit[0], transferable: transferable[0], committedUnits: committedUnits.toString(), reason: bytesReason(canCommit[1]) ?? bytesReason(transferable[1]) }, authority: { configured: authority[3], revoked: authority[2], ensRoleLive }, policy: { configured: policy[3], mode: "LIVE_SIMULATION" } }, finalFinancialSafety: { state: outcome === "PREPARATION_READY" ? "ENFORCED_AT_RELEASE" : "BLOCKED", previewAvailable: false }, blockingReasons: reasons, proofReferences: ["/docs/ethonline-2026/proof/hedera-facility-deployment.json", "/docs/ethonline-2026/proof/ens-authority-lifecycle.json"] };
  } catch (error) { return unavailable(replacement, requestedUnits, "FACILITY_UNAVAILABLE", (error as Error).message.slice(0, 180)); }
}

function unavailable(replacement: string, units: bigint, outcome: "FACILITY_UNAVAILABLE" | "REPLACEMENT_UNSAFE", reason: string): SubstitutionReadiness { return { outcome, facilityId: HEDERA_FACILITY.id, homeDomain: "hedera:testnet:296", observedAt: new Date().toISOString(), observedAtBlock: "UNKNOWN", request: { replacement, requestedUnits: units.toString() }, current: { facilityStatus: "UNKNOWN", riskEpoch: "UNKNOWN", collateralAssetId: "UNKNOWN", collateralInstrumentRef: "UNKNOWN", collateralCommittedUnits: "UNKNOWN", substitutionState: "UNKNOWN" }, replacementIdentity: null, checks: { ats: { canCommit: false, transferable: false, committedUnits: "UNKNOWN", reason: null }, authority: { configured: false, revoked: false, ensRoleLive: false }, policy: { configured: false, mode: "LIVE_SIMULATION" } }, finalFinancialSafety: { state: "BLOCKED", previewAvailable: false }, blockingReasons: [reason], proofReferences: [] }; }
function bytesReason(value: string) { return /^0x0+$/.test(value) ? null : value; }
