// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {MerkleLib} from "../src/libraries/MerkleLib.sol";

/**
 * MerkleLib must agree with the `merkleRoot` in packages/schemas, bit for bit.
 *
 * The offchain pipeline computes the root it intends to commit and PassportRegistry recomputes it
 * from the evidence cited. Those are two independent implementations of one function. If they
 * disagree anywhere, every honest Passport built on the disputed shape is rejected onchain with an
 * error that points at the evidence rather than at the disagreement, and the failure looks like
 * corrupt data instead of a bug.
 *
 * Vectors are generated by `scripts/gen-merkle-vectors.mjs` from the TypeScript implementation,
 * never hand-written here — a vector transcribed by hand is a third implementation.
 */
contract MerkleConformanceTest is Test {
    function test_solidityAgreesWithTypescriptOnEveryVector() public view {
        string memory json = vm.readFile("../fixtures/canonical/merkle-vectors.json");
        // `count` is read from the file rather than derived: forge's JSON path support has no
        // length operator, and a loop bounded by a value it cannot compute would iterate zero
        // times and report success on nothing.
        uint256 count = vm.parseJsonUint(json, ".count");
        assertGt(count, 0, "no vectors: the generator did not run");

        for (uint256 i = 0; i < count; i++) {
            string memory at = string.concat(".vectors[", vm.toString(i), "]");
            bytes32[] memory leaves = vm.parseJsonBytes32Array(json, string.concat(at, ".leaves"));
            bytes32 expected = vm.parseJsonBytes32(json, string.concat(at, ".root"));
            assertEq(MerkleLib.root(leaves), expected, vm.parseJsonString(json, string.concat(at, ".name")));
        }
    }

    // -------------------------------------------------------------- properties

    function test_singleLeafIsItsOwnRoot() public pure {
        bytes32[] memory one = new bytes32[](1);
        one[0] = keccak256("only");
        assertEq(MerkleLib.root(one), one[0]);
    }

    function test_emptyIsRejectedRatherThanReturningTheZeroRoot() public {
        // The TypeScript side returns bytes32(0) for an empty set, which is a reasonable value for
        // a pure function and a terrible one for an authorisation check: PassportRegistry already
        // rejects a zero evidenceRoot, so an empty set that quietly produced one would collide two
        // distinct failures into a single confusing error. Rejecting here keeps them apart.
        bytes32[] memory none = new bytes32[](0);
        vm.expectRevert(MerkleLib.NoLeaves.selector);
        this.rootOf(none);
    }

    function test_duplicateLeavesAreRejected() public {
        bytes32[] memory dup = new bytes32[](2);
        dup[0] = keccak256("same");
        dup[1] = keccak256("same");
        vm.expectRevert(abi.encodeWithSelector(MerkleLib.LeavesNotStrictlyAscending.selector, uint256(1)));
        this.rootOf(dup);
    }

    /// The high bit must not be read as a sign. A comparison over int256 sorts these backwards and
    /// produces a different root for the same set.
    function test_highBitValuesSortAsUnsigned() public pure {
        bytes32[] memory pair = new bytes32[](2);
        pair[0] = bytes32(uint256(type(int256).max));
        pair[1] = bytes32(uint256(1) << 255);
        assertEq(
            MerkleLib.root(pair),
            keccak256(abi.encode(bytes32(uint256(type(int256).max)), bytes32(uint256(1) << 255)))
        );
    }

    function testFuzz_rootIsStableAcrossRepeatedCalls(bytes32 a, bytes32 b, bytes32 c) public pure {
        vm.assume(uint256(a) < uint256(b) && uint256(b) < uint256(c));
        bytes32[] memory first = new bytes32[](3);
        (first[0], first[1], first[2]) = (a, b, c);
        bytes32[] memory second = new bytes32[](3);
        (second[0], second[1], second[2]) = (a, b, c);
        assertEq(MerkleLib.root(first), MerkleLib.root(second));
    }

    /// `root` hashes in place over caller-owned memory. This pins the fact that the caller's array
    /// is consumed, so nobody later assumes it survives and reads a half-overwritten tree.
    function test_theInputArrayIsConsumed() public pure {
        bytes32[] memory leaves = new bytes32[](4);
        for (uint256 i = 0; i < 4; i++) {
            leaves[i] = bytes32(uint256(i + 1));
        }
        bytes32 expected = MerkleLib.root(_copy(leaves));

        bytes32 r = MerkleLib.root(leaves);
        assertEq(r, expected);
        assertEq(leaves[0], r, "root is left at index 0");
    }

    function _copy(bytes32[] memory src) private pure returns (bytes32[] memory out) {
        out = new bytes32[](src.length);
        for (uint256 i = 0; i < src.length; i++) {
            out[i] = src[i];
        }
    }

    /// External so `vm.expectRevert` has a call boundary to catch on a library revert.
    function rootOf(bytes32[] memory leaves) external pure returns (bytes32) {
        return MerkleLib.root(leaves);
    }
}
