#!/usr/bin/env node
/**
 * Deployer key management and funding check.
 *
 *   node scripts/deployer.mjs            # report the current deployer and its balance
 *   node scripts/deployer.mjs --create   # generate a key into .env if none exists
 *
 * The private key is written only to .env, which is gitignored. It is never printed in full,
 * never committed, and never written to any file the repository tracks. A deploy key that ends
 * up in git history is a deploy key that has to be rotated, and rotating means redeploying.
 */

import { readFileSync, writeFileSync, existsSync, appendFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { createPublicClient, http, formatEther } from "viem";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const envPath = resolve(repoRoot, ".env");

const CHAINS = {
  1952: {
    name: "X Layer Testnet",
    rpc: process.env.XLAYER_TESTNET_RPC_URL ?? "https://testrpc.xlayer.tech",
    explorer: "https://www.oklink.com/x-layer-testnet",
    faucet: "https://www.okx.com/xlayer/faucet",
  },
  196: {
    name: "X Layer",
    rpc: process.env.XLAYER_RPC_URL ?? "https://rpc.xlayer.tech",
    explorer: "https://www.oklink.com/xlayer",
    faucet: null,
  },
};

const chainId = Number(process.env.XLAYER_CHAIN_ID ?? 1952);
const chain = CHAINS[chainId];
if (!chain) {
  console.error(`XLAYER_CHAIN_ID=${chainId} is not an X Layer chain (expected 196 or 1952).`);
  process.exit(1);
}

function readEnvFile() {
  if (!existsSync(envPath)) return {};
  const out = {};
  for (const line of readFileSync(envPath, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (m) out[m[1]] = m[2].trim();
  }
  return out;
}

function resolveKey({ create }) {
  const fromEnv = process.env.DEPLOYER_PRIVATE_KEY;
  if (fromEnv) return { key: fromEnv, source: "environment" };

  const fromFile = readEnvFile().DEPLOYER_PRIVATE_KEY;
  if (fromFile) return { key: fromFile, source: ".env" };

  if (!create) return { key: null, source: null };

  const key = generatePrivateKey();
  if (!existsSync(envPath)) {
    writeFileSync(envPath, "# Generated by scripts/deployer.mjs. Gitignored. Never commit.\n");
  }
  appendFileSync(envPath, `\nDEPLOYER_PRIVATE_KEY=${key}\n`);
  return { key, source: "generated" };
}

const create = process.argv.includes("--create");
const { key, source } = resolveKey({ create });

if (!key) {
  console.log("");
  console.log("No deployer key is configured.");
  console.log("");
  console.log("  node scripts/deployer.mjs --create    generate one into .env (gitignored)");
  console.log("  export DEPLOYER_PRIVATE_KEY=0x...     or supply your own");
  console.log("");
  process.exit(2);
}

const account = privateKeyToAccount(key);
const client = createPublicClient({ transport: http(chain.rpc) });

let balance = null;
let rpcError = null;
try {
  balance = await client.getBalance({ address: account.address });
} catch (e) {
  rpcError = e.shortMessage ?? e.message;
}

console.log("");
console.log(`Deployer     ${account.address}`);
console.log(`Key source   ${source}`);
console.log(`Chain        ${chain.name} (${chainId})`);
console.log(`RPC          ${chain.rpc}`);

if (rpcError) {
  console.log(`Balance      unavailable — ${rpcError}`);
  console.log("");
  console.log("BLOCKED: cannot reach the RPC to read the deployer balance.");
  process.exit(3);
}

const okb = formatEther(balance);
console.log(`Balance      ${okb} OKB`);
console.log(`Explorer     ${chain.explorer}/address/${account.address}`);
console.log("");

// A full core deployment is ten contracts. Measured against the current bytecode sizes this
// lands well under 0.05 OKB on X Layer, but the threshold is deliberately generous: running out
// of gas halfway through a deployment leaves a partially wired protocol, which is worse than
// not starting.
const REQUIRED_WEI = 50_000_000_000_000_000n; // 0.05 OKB

if (balance < REQUIRED_WEI) {
  console.log("BLOCKED: deployer is not funded.");
  console.log("");
  console.log(`  Needs   ~${formatEther(REQUIRED_WEI)} OKB for a full core deployment`);
  console.log(`  Has      ${okb} OKB`);
  console.log(`  Address  ${account.address}`);
  if (chain.faucet) console.log(`  Faucet   ${chain.faucet}`);
  console.log("");
  console.log("Every other build target is unaffected and should keep running:");
  console.log("  make test  make test-differential  make build  make verify-integrations");
  console.log("");
  process.exit(4);
}

console.log("Funded. `make deploy-testnet` can proceed.");
console.log("");
