import Link from "next/link";
import { notFound } from "next/navigation";
import { Footer, Nav, Notice } from "@/components/primitives";
import { AUTHORITY_PROOFS, HEDERA_FACILITY, REFUSED_SUBSTITUTION, SUCCESSFUL_SUBSTITUTION } from "@/lib/institutional-proof";
import { InstitutionalLiveState } from "@/components/institutional-live-state";

export default async function FacilityPage({ params }: { params: Promise<{ facilityId: string }> }) {
  const { facilityId } = await params;
  if (facilityId.toLowerCase() !== HEDERA_FACILITY.id.toLowerCase()) notFound();
  const facility = HEDERA_FACILITY;
  return <><Nav /><main><section className="section"><div className="shell stack" style={{ gap: 22 }}>
    <div><div className="micro">Institutional facility · {facility.homeDomain}</div><h1 className="heading-lg" style={{ margin: "12px 0" }}>Term secured credit</h1><p className="muted mono">{facility.id}</p></div>
    <Notice tone="warn" title="Read-only institutional proof surface">The live testnet mechanism was operated through purpose-built operator tooling. This browser never uses Hedera operator, CRE reporter, Privy quorum, or deployer credentials. Existing collateral remains unchanged from this page.</Notice>
    <InstitutionalLiveState facilityId={facility.id} />
    <section className="card"><div className="row-between"><div className="micro">Current facility state</div><span className="risk risk-NORMAL">ACTIVE</span></div><div className="grid-2" style={{ gap: 16, marginTop: 18 }}><Field label="Home domain" value={facility.homeDomain}/><Field label="Facility type" value={facility.type.replace(/_/g, " ")}/><Field label="Borrower" value={short(facility.borrower)}/><Field label="Capital provider" value={short(facility.lender)}/><Field label="Settlement" value={`${facility.settlement.label} · ${facility.settlement.decimals} decimals`}/><Field label="Outstanding debt" value="Not emitted by the preserved public proof artifact"/><Field label="RiskEpoch" value={facility.riskEpoch}/><Field label="Maturity" value={new Date(facility.maturityAt * 1000).toISOString().slice(0, 10)}/></div></section>
    <section className="card"><div className="micro">Current collateral truth</div><h2 className="heading" style={{ margin: "10px 0" }}>Series {facility.currentCollateral.series} · Hedera ATS Hold</h2><div className="grid-2" style={{ gap: 16 }}><Field label="Hedera security" value={facility.currentCollateral.id}/><Field label="Instrument identity" value={short(facility.currentCollateral.assetId)}/><Field label="Committed quantity" value={facility.currentCollateral.committed}/><Field label="State" value="Transferable; committed through ATS Hold"/></div><p className="caption" style={{ marginTop: 16 }}>The ATS Hold is the authoritative custody state. The asset record is not a generic ERC-20 balance or a browser-side accounting value.</p></section>
    <section className="card"><div className="micro">Completed collateral substitution</div><h2 className="heading" style={{ margin: "10px 0" }}>A → B without unwinding the facility</h2><p className="muted">At commitment, A and B were both held at 150,000 units. Only after B was committed did the facility release A.</p><ol className="steps" style={{ marginTop: 18 }}>{SUCCESSFUL_SUBSTITUTION.steps.map((step, index) => <li data-state="done" key={step}><span className="step-dot">✓</span><span><strong>{step}</strong>{index === 5 ? <span className="caption" style={{ display: "block" }}>A: {SUCCESSFUL_SUBSTITUTION.committed.A}; B: {SUCCESSFUL_SUBSTITUTION.committed.B}. Both remained committed.</span> : null}</span></li>)}</ol><div className="row" style={{ gap: 12, marginTop: 14 }}><Link className="btn btn-ghost" href={`/institutional/facilities/${facility.id}/substitute`}>Inspect substitution receipt</Link><Link className="btn" href={`/institutional/facilities/${facility.id}/replace`}>Replace collateral</Link></div></section>
    <section className="grid-3" style={{ gap: 18 }}><Authority title="Institutional authority" provider={AUTHORITY_PROOFS.ens.provider} status={AUTHORITY_PROOFS.ens.proofLevel} rows={[["Name", AUTHORITY_PROOFS.ens.name], ["Role", AUTHORITY_PROOFS.ens.role], ["Observed block", String(AUTHORITY_PROOFS.ens.observedBlock)], ["Current status", AUTHORITY_PROOFS.ens.currentStatus]]} note={AUTHORITY_PROOFS.ens.limitation}/><Authority title="Organization approval" provider={AUTHORITY_PROOFS.privy.provider} status={AUTHORITY_PROOFS.privy.proofLevel} rows={[["Wallet", short(AUTHORITY_PROOFS.privy.wallet)], ["Control", AUTHORITY_PROOFS.privy.quorum]]} note={AUTHORITY_PROOFS.privy.limitation}/><Authority title="Confidential lender policy" provider={AUTHORITY_PROOFS.cre.provider} status={AUTHORITY_PROOFS.cre.proofLevel} rows={[["Decision", AUTHORITY_PROOFS.cre.decision], ["Policy commitment", short(AUTHORITY_PROOFS.cre.policyCommitment)], ["Workflow", `Version ${AUTHORITY_PROOFS.cre.workflowVersion}`]]} note={AUTHORITY_PROOFS.cre.limitation}/></section>
    <section className="card"><div className="micro">Refused replacement</div><h2 className="heading" style={{ margin: "10px 0" }}>Series C was not accepted</h2><Notice tone="stop" title="Collateral replacement refused">{REFUSED_SUBSTITUTION.reason}. Existing collateral remained secured ({REFUSED_SUBSTITUTION.currentCollateral} units), the candidate commitment remained {REFUSED_SUBSTITUTION.candidateCollateral}, and the facility remained {REFUSED_SUBSTITUTION.facilityStatus}. An authorized operator must resolve the ATS pause before a new request can succeed.</Notice></section>
  </div></section></main><Footer /></>;
}

function Field({ label, value }: { label: string; value: string }) { return <div><div className="micro">{label}</div><div style={{ marginTop: 6, fontWeight: 500, overflowWrap: "anywhere" }}>{value}</div></div> }
function Authority({ title, provider, status, rows, note }: { title: string; provider: string; status: string; rows: readonly (readonly [string, string])[]; note: string }) { return <section className="card"><div className="micro">{title}</div><h2 className="subheading" style={{ margin: "10px 0 4px" }}>{provider}</h2><span className="tag">{status.replace(/_/g, " ")}</span>{rows.map(([label, value]) => <div key={label} style={{ marginTop: 12 }}><div className="caption">{label}</div><div className="caption" style={{ color: "var(--graphite)" }}>{value}</div></div>)}<p className="caption" style={{ margin: "14px 0 0" }}>{note}</p></section> }
function short(value: string) { return `${value.slice(0, 10)}…${value.slice(-8)}`; }
